### ISSUE TITLE
请问下打包成功但是运行时报错？

### ISSUE THREAD

**Issue by songuu** [QDMarkMan/CodeBlog#1]
uncaught exception:
error: enotdir, not a direction
at createError(electron.js2c/asar.js:16:17)

**Comment by QDMarkMan** [comment]
集成了Python ? 你可以看看这个[https://stackoverflow.com/questions/59566904/no-such-file-or-directory-inside-app-asar-electron-nodejs](https://stackoverflow.com/questions/59566904/no-such-file-or-directory-inside-app-asar-electron-nodejs)

**Comment by QDMarkMan** [comment]
> uncaught exception:
> error: enotdir, not a direction
> at createError(electron.js2c/asar.js:16:17)

集成了Python ? 你可以看看这个[https://stackoverflow.com/questions/59566904/no-such-file-or-directory-inside-app-asar-electron-nodejs](https://stackoverflow.com/questions/59566904/no-such-file-or-directory-inside-app-asar-electron-nodejs)
